language: python
python:
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
  - pip install -r requirements.txt
  - pip install html5validator

script:
  - cactus build --verbose
  - html5validator --root .build --show-warnings --also-check-css
