language: python
python:
  - "2.7"

before_install:
  - pip install https://github.com/koenbok/Cactus/archive/v3.zip
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - cactus build
  - cd .build 
  - for file in *.html; do python ../html5check.py -eh $file; done;
